In [1]:
import pandas as pd
import sys
import os
import importlib

sys.path.append(os.path.abspath(".."))

import src.features
importlib.reload(src.features)

In [2]:
df = pd.read_csv("../data/raw/nba_players_2023_24_raw.csv")
df.head()

,Game_ID,GAME_DATE,MATCHUP,WL,MIN,FGM,FGA,FG3M,FG3A,FTM,FTA,REB,AST,TOV,STL,BLK,PTS,PLUS_MINUS,PLAYER_NAME,PLAYER_ID
0,22300277,2023-12-01,DAL vs. MEM,L,4,0,1,0,1,1,2,1,0,0,0,0,1,4,A.J. Lawson,1630639
1,22300287,2023-12-02,DAL vs. OKC,L,19,4,10,3,7,1,2,0,2,0,0,1,12,9,A.J. Lawson,1630639
2,22301213,2023-12-06,DAL vs. UTA,W,7,2,2,0,0,0,0,1,0,0,0,0,4,7,A.J. Lawson,1630639
3,22301226,2023-12-08,DAL @ POR,W,7,1,3,0,2,0,0,1,0,0,0,0,2,-4,A.J. Lawson,1630639
4,22300299,2023-12-11,DAL @ MEM,W,14,2,7,0,4,0,0,1,1,1,0,0,4,1,A.J. Lawson,1630639

In [3]:
model_df = src.features.prepare_model_dataset(df)
model_df.head()

,PLAYER_NAME,PLAYER_ID,GAME_DATE,MATCHUP,PTS,HOME,days_rest,pts_last3,pts_last5,pts_last10,...,fga_last3,fga_last5,fg3a_last5,fta_last5,reb_last5,ast_last5,pts_std_last5,pts_trend,min_trend,fga_trend
0,A.J. Lawson,1630639,2023-12-22,DAL @ HOU,8,0,2.0,2.000000,1.6,3.1,...,1.333333,1.0,0.4,0.4,0.4,0.0,2.607681,-1.5,1.866667,0.333333
1,A.J. Lawson,1630639,2023-12-23,DAL vs. SAS,17,1,1.0,4.666667,3.2,3.8,...,2.666667,1.8,0.6,0.8,0.8,0.2,3.633180,-0.6,4.600000,0.866667
2,A.J. Lawson,1630639,2023-12-25,DAL @ PHX,0,0,2.0,8.333333,6.2,4.3,...,4.666667,3.6,1.4,0.8,2.2,0.8,7.014271,1.9,4.133333,1.066667
3,A.J. Lawson,1630639,2024-01-03,DAL vs. POR,3,1,9.0,8.333333,6.2,3.9,...,5.333333,4.0,1.8,0.8,2.4,0.8,7.014271,2.3,4.666667,1.333333
4,A.J. Lawson,1630639,2024-01-05,DAL vs. POR,14,1,2.0,6.666667,5.6,4.0,...,5.333333,4.0,1.6,0.4,2.0,0.8,7.162402,1.6,1.066667,1.333333

In [4]:
model_df.shape

(13201, 22)

In [5]:
model_df["PLAYER_NAME"].nunique()

264

In [6]:
model_df.to_csv("../data/processed/nba_players_model_dataset.csv", index=False)
print("Saved to ../data/processed/nba_players_model_dataset.csv")

Saved to ../data/processed/nba_players_model_dataset.csv